### ISSUE TITLE
Rountrip the IR one more time in the test cases that use the generic printer

### ISSUE THREAD

**Issue by jmgorius** [maerhart/llhd#29]
When using `mlir-print-op-generic`, the IR should go three times through `llhdc`:
- `llhdc -mlir-print-op-generic` checks that we can parse the content of the test file.
- `llhdc` then checks that we can parse the generic form and pretty-print it.
- An additional `llhdc` checks that we can parse the output of the pretty-printer, which may be different from the contents of the input test file.

This would make it easier to catch errors during parsing/printing refactorings.

**Comment by rodonisi** [comment]
Thanks for the input! I didn't think that third pass through llhdc, I'll add it where we're already using the `mlir-print-op-generic`
